version: 0.2
env:
    variables:
        APP_NAME: "nuxt-app"
phases:
    install:
        runtime-versions:
            nodejs: 20.x
        commands:
            - echo install pnpm ....
            - npm install -g pnpm@8.14.0
            - pnpm --version
    build:
        commands:
            - echo install pnpm dependencies
            - pnpm install --frozen-lockfile
            - echo pnpm run process started now....
            - pnpm run dev-generate
    post_build:
        commands:
            - echo build process finished, we should upload to S3 now
            - ls
            # - aws s3 sync  .output/public/ s3://vhypotenuse-edc-portal-site-3444 --delete
